name: Deploy to AWS S3
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::159625156332:role/GH
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        
      - name: Install NPM dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy static site to S3 bucket
        run: npm run deploy
